#!/bin/sh -e
#
# memoize

CACHEDIR="${CACHEDIR:-${XDG_CACHE_HOME:-$HOME/.cache}/memoize}"

tmp="$(mktemp)"
trap 'rm $tmp' EXIT
cat - > "$tmp"

sum_args="$(echo "$@" | md5sum | cut -d' ' -f1)"
sum_input="$(md5sum "$tmp" | cut -d' ' -f1)"
cachefile="$CACHEDIR/$sum_args-$sum_input"

if [ -f "$cachefile" ]
then
	cat "$cachefile"
else
	< "$tmp" exec "$@" | tee "$cachefile"
fi
