on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux, darwin, openbsd, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build
        run: go build -v ./...
        env:
            CGO_ENABLED: 0
            GOOS: ${{ matrix.goos }}
            GOARCH: ${{ matrix.goarch }}
            GOPROXY: "https://proxy.golang.org"
