on: [push, pull_request]
jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go build .
        env:
            GOPROXY: "https://proxy.golang.org"
