on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: go build -v ./...
    - uses: softprops/action-gh-release@v1
      with:
        files: httpipe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

